const prisma = require("../src/configs/prisma");
const bcrypt = require("bcryptjs");

const hashedPassword = bcrypt.hashSync("123456", 10);

const userData = [
  {
    email: "admin01@mail.com",
    password: hashedPassword,
    firstName: "Admin",
    lastName: "Leo",
    phone: "0123456789",
    gender: "MALE",
    role: "ADMIN",
  },
  {
    email: "admin02@mail.com",
    password: hashedPassword,
    firstName: "Admin",
    lastName: "Ploy",
    phone: "0123456789",
    gender: "FEMALE",
    role: "ADMIN",
  },
  {
    email: "admin03@mail.com",
    password: hashedPassword,
    firstName: "Admin",
    lastName: "Bell",
    phone: "0123456789",
    gender: "OTHER",
    role: "ADMIN",
  },
  {
    email: "admin04@mail.com",
    password: hashedPassword,
    firstName: "Admin",
    lastName: "Big",
    phone: "0123456789",
    gender: "MALE",
    role: "ADMIN",
  },
  {
    email: "admin05@mail.com",
    password: hashedPassword,
    firstName: "Admin",
    lastName: "Boeing",
    phone: "0123456789",
    gender: "FEMALE",
    role: "ADMIN",
  },
  {
    email: "user01@mail.com",
    password: hashedPassword,
    firstName: "User",
    lastName: "One",
    phone: "0123456789",
    gender: "MALE",
    role: "USER",
  },
  {
    email: "user02@mail.com",
    password: hashedPassword,
    firstName: "User",
    lastName: "Two",
    phone: "0123456789",
    gender: "FEMALE",
    role: "USER",
  },
  {
    email: "user03@mail.com",
    password: hashedPassword,
    firstName: "User",
    lastName: "Three",
    phone: "0123456789",
    gender: "OTHER",
    role: "USER",
  },
  {
    email: "user04@mail.com",
    password: hashedPassword,
    firstName: "User",
    lastName: "Four",
    phone: "0123456789",
    gender: "MALE",
    role: "USER",
  },
  {
    email: "user05@mail.com",
    password: hashedPassword,
    firstName: "User",
    lastName: "Five",
    phone: "0123456789",
    gender: "FEMALE",
    role: "USER",
  },
  {
    email: "partner01@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "One",
    phone: "0123456789",
    gender: "MALE",
    role: "PARTNER",
  },
  {
    email: "partner02@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Two",
    phone: "0123456789",
    gender: "FEMALE",
    role: "PARTNER",
  },
  {
    email: "partner03@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Three",
    phone: "0123456789",
    gender: "OTHER",
    role: "PARTNER",
  },
  {
    email: "partner04@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Four",
    phone: "0123456789",
    gender: "MALE",
    role: "PARTNER",
  },
  {
    email: "partner05@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Five",
    phone: "0123456789",
    gender: "FEMALE",
    role: "PARTNER",
  },
  {
    email: "partner06@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Six",
    phone: "0123456789",
    gender: "MALE",
    role: "PARTNER",
  },
  {
    email: "partner07@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Seven",
    phone: "0123456789",
    gender: "FEMALE",
    role: "PARTNER",
  },
  {
    email: "partner08@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Eight",
    phone: "0123456789",
    gender: "OTHER",
    role: "PARTNER",
  },
  {
    email: "partner09@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Nine",
    phone: "0123456789",
    gender: "MALE",
    role: "PARTNER",
  },
  {
    email: "partner10@mail.com",
    password: hashedPassword,
    firstName: "Partner",
    lastName: "Ten",
    phone: "0123456789",
    gender: "FEMALE",
    role: "PARTNER",
  }
];
const partnerData = [
  {
    companyName: "GreenTech Solutions",
    address: "123 Green Street, Eco City, EC12345",
    userId: 11,
    taxNo: "1012345678901",
    bankName: "EcoBank",
    bankAccount: "123456789012",
  },
  {
    companyName: "Alpha Innovations",
    address: "456 Alpha Lane, Tech Town, TT67890",
    userId: 12,
    taxNo: "2012345678902",
    bankName: "TechBank",
    bankAccount: "234567890123",
  },
  {
    companyName: "Culinary Delights Inc.",
    address: "789 Flavor Avenue, Food City, FC11223",
    userId: 13,
    taxNo: "3012345678903",
    bankName: "Culinary Bank",
    bankAccount: "345678901234",
  },
  {
    companyName: "Health & Wellness Co.",
    address: "101 Wellness Way, Health City, HC44556",
    userId: 14,
    taxNo: "4012345678904",
    bankName: "Wellness Bank",
    bankAccount: "456789012345",
  },
  {
    companyName: "Travel Ventures",
    address: "202 Adventure Rd, Travel Town, TT33445",
    userId: 15,
    taxNo: "5012345678905",
    bankName: "TravelBank",
    bankAccount: "567890123456",
  },
  {
    companyName: "Fashion Forward Ltd.",
    address: "303 Style Blvd, Fashion City, FC77889",
    userId: 16,
    taxNo: "6012345678906",
    bankName: "Style Bank",
    bankAccount: "678901234567",
  },
  {
    companyName: "EduWorld Academy",
    address: "404 Learning Lane, Education City, EC88900",
    userId: 17,
    taxNo: "7012345678907",
    bankName: "EduBank",
    bankAccount: "789012345678",
  },
  {
    companyName: "EcoSmart Solutions",
    address: "505 Sustainability St, Green City, GC55432",
    userId: 18,
    taxNo: "8012345678908",
    bankName: "EcoSmart Bank",
    bankAccount: "890123456789",
  },
  {
    companyName: "TechWave Corp.",
    address: "606 Innovation Ave, Silicon Valley, SV12345",
    userId: 19,
    taxNo: "9012345678909",
    bankName: "Wave Bank",
    bankAccount: "901234567890",
  },
  {
    companyName: "Artistic Visions",
    address: "707 Creativity Way, Art Town, AT98765",
    userId: 20,
    taxNo: "1022345678900",
    bankName: "ArtBank",
    bankAccount: "012345678901",
  }
];
const hotelData = [
  {
    name: "The Grand Mirage",
    detail: "Luxurious beachfront resort with stunning ocean views and world-class amenities.",
    address: "123 Ocean Ave, Bali, Indonesia",
    lat: -8.409518,
    lng: 115.188916,
    partnerId: 1,
    img: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-10T15:00:00Z",
    checkoutTime: "2024-11-12T12:00:00Z",
    star: 5,
    phone: "+62 361 1234567",
    webPage: "www.grandmirage.com",
    isActive: true,
    facilitiesHotelId: 1,
  },
  {
    name: "City Lights Inn",
    detail: "Modern city center hotel ideal for business and leisure travelers.",
    address: "456 Main St, San Francisco, CA, USA",
    lat: 37.774929,
    lng: -122.419418,
    partnerId: 2,
    img: "https://images.pexels.com/photos/594077/pexels-photo-594077.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-12T14:00:00Z",
    checkoutTime: "2024-11-13T11:00:00Z",
    star: 4,
    phone: "+1 415 6781234",
    webPage: "www.citylightsinn.com",
    isActive: true,
    facilitiesHotelId: 2,
  },
  {
    name: "Mountain Haven Lodge",
    detail: "Charming lodge nestled in the heart of the Rocky Mountains.",
    address: "789 Mountain Rd, Aspen, CO, USA",
    lat: 39.1911,
    lng: -106.8175,
    partnerId: 3,
    img: "https://images.pexels.com/photos/261395/pexels-photo-261395.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-14T16:00:00Z",
    checkoutTime: "2024-11-16T10:00:00Z",
    star: 4,
    phone: "+1 970 5557890",
    webPage: "www.mountainhaven.com",
    isActive: true,
    facilitiesHotelId: 3,
  },
  {
    name: "Desert Oasis Resort",
    detail: "Exclusive desert resort with spa, fine dining, and private villas.",
    address: "123 Oasis Blvd, Palm Springs, CA, USA",
    lat: 33.8303,
    lng: -116.5453,
    partnerId: 4,
    img: "https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-17T14:00:00Z",
    checkoutTime: "2024-11-19T11:00:00Z",
    star: 5,
    phone: "+1 760 6781234",
    webPage: "www.desertoasisresort.com",
    isActive: true,
    facilitiesHotelId: 4,
  },
  {
    name: "Urban Comfort Suites",
    detail: "Contemporary suites with full amenities located in the heart of downtown.",
    address: "101 Downtown St, Chicago, IL, USA",
    lat: 41.8781,
    lng: -87.6298,
    partnerId: 5,
    img: "https://images.pexels.com/photos/1145257/pexels-photo-1145257.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-20T15:00:00Z",
    checkoutTime: "2024-11-21T12:00:00Z",
    star: 4,
    phone: "+1 312 4567890",
    webPage: "www.urbancomfortsuites.com",
    isActive: true,
    facilitiesHotelId: 5,
  },
  {
    name: "Paradise Cove",
    detail: "A tranquil retreat with oceanfront bungalows and spa services.",
    address: "456 Seaside Dr, Maui, Hawaii, USA",
    lat: 20.7984,
    lng: -156.3319,
    partnerId: 6,
    img: "https://images.pexels.com/photos/949406/pexels-photo-949406.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-22T15:00:00Z",
    checkoutTime: "2024-11-24T11:00:00Z",
    star: 5,
    phone: "+1 808 9876543",
    webPage: "www.paradisecove.com",
    isActive: true,
    facilitiesHotelId: 6,
  },
  {
    name: "Metro Plaza",
    detail: "Convenient and affordable hotel located in the heart of the city.",
    address: "789 Central Ave, New York, NY, USA",
    lat: 40.7128,
    lng: -74.0060,
    partnerId: 7,
    img: "https://images.pexels.com/photos/322154/pexels-photo-322154.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-24T15:00:00Z",
    checkoutTime: "2024-11-25T11:00:00Z",
    star: 3,
    phone: "+1 212 1234567",
    webPage: "www.metroplaza.com",
    isActive: true,
    facilitiesHotelId: 7,
  },
  {
    name: "Tropical Breeze Inn",
    detail: "Family-friendly hotel with tropical garden views and a large swimming pool.",
    address: "101 Beach Rd, Phuket, Thailand",
    lat: 7.8804,
    lng: 98.3923,
    partnerId: 8,
    img: "https://images.pexels.com/photos/804878/pexels-photo-804878.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-26T15:00:00Z",
    checkoutTime: "2024-11-27T11:00:00Z",
    star: 4,
    phone: "+66 76 123456",
    webPage: "www.tropicalbreezeinn.com",
    isActive: true,
    facilitiesHotelId: 8,
  },
  {
    name: "The Urbanite",
    detail: "Stylish and eco-friendly hotel close to shopping and dining destinations.",
    address: "202 Modern St, Los Angeles, CA, USA",
    lat: 34.0522,
    lng: -118.2437,
    partnerId: 9,
    img: "https://images.pexels.com/photos/2403017/pexels-photo-2403017.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-27T15:00:00Z",
    checkoutTime: "2024-11-29T11:00:00Z",
    star: 4,
    phone: "+1 323 8765432",
    webPage: "www.theurbanite.com",
    isActive: true,
    facilitiesHotelId: 9,
  },
  {
    name: "Countryside Escape",
    detail: "Rustic lodge with beautiful countryside views and outdoor activities.",
    address: "404 Countryside Ln, Vermont, USA",
    lat: 44.5588,
    lng: -72.5778,
    partnerId: 10,
    img: "https://images.pexels.com/photos/6010421/pexels-photo-6010421.jpeg?auto=compress&cs=tinysrgb&w=600",
    checkinTime: "2024-11-30T15:00:00Z",
    checkoutTime: "2024-12-01T11:00:00Z",
    star: 3,
    phone: "+1 802 6543210",
    webPage: "www.countrysideescape.com",
    isActive: true,
    facilitiesHotelId: 10,
  }
];
const facilitiesHotelsData = [
  {
    isRoomService: true,
    isReception: true,
    isFitness: true,
    isParking: true,
    isEVCharging: true,
    isSwimmingPool: true,
    isRestaurant: true,
    isBreakfast: true,
    isChildren: true,
    isPetFriendly: true,
    isElevator: true,
  },
  {
    isRoomService: true,
    isReception: true,
    isFitness: false,
    isParking: true,
    isEVCharging: false,
    isSwimmingPool: true,
    isRestaurant: false,
    isBreakfast: true,
    isChildren: false,
    isPetFriendly: true,
    isElevator: true,
  },
  {
    isRoomService: false,
    isReception: true,
    isFitness: true,
    isParking: false,
    isEVCharging: true,
    isSwimmingPool: false,
    isRestaurant: true,
    isBreakfast: true,
    isChildren: true,
    isPetFriendly: false,
    isElevator: true,
  },
  {
    isRoomService: true,
    isReception: true,
    isFitness: true,
    isParking: true,
    isEVCharging: false,
    isSwimmingPool: true,
    isRestaurant: true,
    isBreakfast: true,
    isChildren: false,
    isPetFriendly: true,
    isElevator: true,
  },
  {
    isRoomService: true,
    isReception: true,
    isFitness: false,
    isParking: true,
    isEVCharging: true,
    isSwimmingPool: false,
    isRestaurant: false,
    isBreakfast: true,
    isChildren: true,
    isPetFriendly: false,
    isElevator: false,
  },
  {
    isRoomService: true,
    isReception: true,
    isFitness: false,
    isParking: true,
    isEVCharging: false,
    isSwimmingPool: true,
    isRestaurant: true,
    isBreakfast: true,
    isChildren: true,
    isPetFriendly: false,
    isElevator: true,
  },
  {
    isRoomService: false,
    isReception: true,
    isFitness: true,
    isParking: true,
    isEVCharging: true,
    isSwimmingPool: false,
    isRestaurant: false,
    isBreakfast: true,
    isChildren: false,
    isPetFriendly: true,
    isElevator: false,
  },
  {
    isRoomService: true,
    isReception: true,
    isFitness: true,
    isParking: true,
    isEVCharging: true,
    isSwimmingPool: true,
    isRestaurant: true,
    isBreakfast: false,
    isChildren: true,
    isPetFriendly: false,
    isElevator: true,
  },
  {
    isRoomService: false,
    isReception: false,
    isFitness: true,
    isParking: false,
    isEVCharging: false,
    isSwimmingPool: true,
    isRestaurant: true,
    isBreakfast: true,
    isChildren: false,
    isPetFriendly: true,
    isElevator: true,
  },
  {
    isRoomService: true,
    isReception: true,
    isFitness: true,
    isParking: true,
    isEVCharging: false,
    isSwimmingPool: false,
    isRestaurant: true,
    isBreakfast: false,
    isChildren: true,
    isPetFriendly: false,
    isElevator: false,
  }
];
const roomData = [
  {
    name: "Ocean View Suite",
    detail: "Spacious suite with breathtaking ocean views and luxurious amenities.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 500.0,
    recommendPeople: 4,
    size: 60.0,
    hotelId: 1,
    facilityRoomId: 1,
    roomAmount: 10,
  },
  {
    name: "Executive City View",
    detail: "Comfortable room with a stunning view of the city skyline.",
    status: "AVAILABLE",
    type: "DOUBLE",
    price: 350.0,
    recommendPeople: 2,
    size: 35.0,
    hotelId: 1,
    facilityRoomId: 2,
    roomAmount: 15,
  },
  {
    name: "Mountain Retreat Suite",
    detail: "Elegant suite with mountain views and top-of-the-line amenities.",
    status: "UNAVAILABLE",
    type: "SINGLE",
    price: 400.0,
    recommendPeople: 3,
    size: 45.0,
    hotelId: 1,
    facilityRoomId: 3,
    roomAmount: 5,
  },
  {
    name: "Garden Deluxe",
    detail: "Beautiful room overlooking lush garden landscapes.",
    status: "AVAILABLE",
    type: "DOUBLE",
    price: 200.0,
    recommendPeople: 2,
    size: 30.0,
    hotelId: 2,
    facilityRoomId: 4,
    roomAmount: 8,
  },
  {
    name: "Presidential Suite",
    detail: "Luxurious suite with exclusive amenities and exceptional service.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 1000.0,
    recommendPeople: 5,
    size: 90.0,
    hotelId: 2,
    facilityRoomId: 5,
    roomAmount: 2,
  },
  {
    name: "Bungalow Suite",
    detail: "Cozy bungalow suite surrounded by lush gardens.",
    status: "AVAILABLE",
    type: "SINGLE",
    price: 450.0,
    recommendPeople: 3,
    size: 40.0,
    hotelId: 3,
    facilityRoomId: 6,
    roomAmount: 6,
  },
  {
    name: "Standard Twin Room",
    detail: "Comfortable twin room with essential amenities.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 150.0,
    recommendPeople: 2,
    size: 20.0,
    hotelId: 3,
    facilityRoomId: 7,
    roomAmount: 20,
  },
  {
    name: "Family Room",
    detail: "Spacious room with beds for the entire family.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 300.0,
    recommendPeople: 4,
    size: 50.0,
    hotelId: 4,
    facilityRoomId: 8,
    roomAmount: 10,
  },
  {
    name: "Studio Room",
    detail: "Modern studio with city view and kitchenette.",
    status: "AVAILABLE",
    type: "SINGLE",
    price: 200.0,
    recommendPeople: 2,
    size: 30.0,
    hotelId: 4,
    facilityRoomId: 9,
    roomAmount: 12,
  },
  {
    name: "Countryside King",
    detail: "Rustic king room with countryside view.",
    status: "AVAILABLE",
    type: "DOUBLE",
    price: 180.0,
    recommendPeople: 2,
    size: 25.0,
    hotelId: 5,
    facilityRoomId: 10,
    roomAmount: 15,
  },
  {
    name: "Sunset Beachfront Suite",
    detail: "Luxurious suite with stunning sunset views over the beach.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 600.0,
    recommendPeople: 4,
    size: 70.0,
    hotelId: 5,
    facilityRoomId: 11,
    roomAmount: 5,
  },
  {
    name: "Urban Loft",
    detail: "Stylish loft in the heart of the city, perfect for urban explorers.",
    status: "AVAILABLE",
    type: "SINGLE",
    price: 280.0,
    recommendPeople: 2,
    size: 40.0,
    hotelId: 6,
    facilityRoomId: 12,
    roomAmount: 10,
  },
  {
    name: "Riverside Cabin",
    detail: "Charming cabin by the riverside, ideal for nature lovers.",
    status: "UNAVAILABLE",
    type: "DOUBLE",
    price: 320.0,
    recommendPeople: 3,
    size: 50.0,
    hotelId: 6,
    facilityRoomId: 13,
    roomAmount: 4,
  },
  {
    name: "Luxury Garden Villa",
    detail: "Elegant villa with private garden and swimming pool.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 900.0,
    recommendPeople: 6,
    size: 120.0,
    hotelId: 6,
    facilityRoomId: 14,
    roomAmount: 3,
  },
  {
    name: "Cozy Mountain Lodge",
    detail: "Warm and inviting lodge with mountain views.",
    status: "AVAILABLE",
    type: "SINGLE",
    price: 250.0,
    recommendPeople: 2,
    size: 35.0,
    hotelId: 7,
    facilityRoomId: 15,
    roomAmount: 8,
  },
  {
    name: "Elegant City Center Suite",
    detail: "Sophisticated suite with modern amenities in the city center.",
    status: "AVAILABLE",
    type: "DOUBLE",
    price: 450.0,
    recommendPeople: 3,
    size: 60.0,
    hotelId: 7,
    facilityRoomId: 16,
    roomAmount: 7,
  },
  {
    name: "Charming Cottage",
    detail: "Cozy cottage with rustic decor and beautiful surroundings.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 180.0,
    recommendPeople: 2,
    size: 25.0,
    hotelId: 8,
    facilityRoomId: 17,
    roomAmount: 15,
  },
  {
    name: "Penthouse Suite",
    detail: "Spacious penthouse with panoramic views and private terrace.",
    status: "AVAILABLE",
    type: "MASTER",
    price: 1200.0,
    recommendPeople: 5,
    size: 150.0,
    hotelId: 9,
    facilityRoomId: 18,
    roomAmount: 1,
  },
  {
    name: "Classic Double Room",
    detail: "Traditional double room with all essential amenities.",
    status: "AVAILABLE",
    type: "DOUBLE",
    price: 220.0,
    recommendPeople: 2,
    size: 30.0,
    hotelId: 9,
    facilityRoomId: 19,
    roomAmount: 20,
  },
  {
    name: "Seaside Retreat",
    detail: "Relaxing room with direct access to the beach.",
    status: "UNAVAILABLE",
    type: "SINGLE",
    price: 350.0,
    recommendPeople: 2,
    size: 35.0,
    hotelId: 10,
    facilityRoomId: 20,
    roomAmount: 30,
  }
];
const roomImagesData = [
  { img: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 1 },
  { img: "https://images.pexels.com/photos/210265/pexels-photo-210265.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 1 },
  { img: "https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 2 },
  { img: "https://images.pexels.com/photos/2736388/pexels-photo-2736388.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 2 },
  { img: "https://images.pexels.com/photos/271672/pexels-photo-271672.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 2 },
  { img: "https://images.pexels.com/photos/3201735/pexels-photo-3201735.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 3 },
  { img: "https://images.pexels.com/photos/3201758/pexels-photo-3201758.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 3 },
  { img: "https://images.pexels.com/photos/3201767/pexels-photo-3201767.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 3 },
  { img: "https://images.pexels.com/photos/3688261/pexels-photo-3688261.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 4 },
  { img: "https://images.pexels.com/photos/3315291/pexels-photo-3315291.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 4 },
  { img: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 5 },
  { img: "https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 5 },
  { img: "https://images.pexels.com/photos/27638171/pexels-photo-27638171.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 6 },
  { img: "https://images.pexels.com/photos/6236641/pexels-photo-6236641.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 6 },
  { img: "https://images.pexels.com/photos/19799232/pexels-photo-19799232.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 7 },
  { img: "https://images.pexels.com/photos/2598638/pexels-photo-2598638.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 7 },
  { img: "https://images.pexels.com/photos/24877193/pexels-photo-24877193.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 8 },
  { img: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 9 },
  { img: "https://images.pexels.com/photos/3688261/pexels-photo-3688261.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 10 },
  { img: "https://images.pexels.com/photos/2736388/pexels-photo-2736388.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 10 },
  { img: "https://images.pexels.com/photos/271643/pexels-photo-271643.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 11 },
  { img: "https://images.pexels.com/photos/2134224/pexels-photo-2134224.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 11 },
  { img: "https://images.pexels.com/photos/14022458/pexels-photo-14022458.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 12 },
  { img: "https://images.pexels.com/photos/12805883/pexels-photo-12805883.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 13 },
  { img: "https://images.pexels.com/photos/27729152/pexels-photo-27729152.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 14 },
  { img: "https://images.pexels.com/photos/12652920/pexels-photo-12652920.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 14 },
  { img: "https://images.pexels.com/photos/28200535/pexels-photo-28200535.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 15 },
  { img: "https://images.pexels.com/photos/27562182/pexels-photo-27562182.png?auto=compress&cs=tinysrgb&w=600", roomId: 15 },
  { img: "https://images.pexels.com/photos/29080576/pexels-photo-29080576.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 16 },
  { img: "https://images.pexels.com/photos/29080565/pexels-photo-29080565.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 16 },
  { img: "https://images.pexels.com/photos/5461604/pexels-photo-5461604.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 17 },
  { img: "https://images.pexels.com/photos/5461600/pexels-photo-5461600.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 17 },
  { img: "https://images.pexels.com/photos/22469110/pexels-photo-22469110.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 18 },
  { img: "https://images.pexels.com/photos/3688261/pexels-photo-3688261.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 19 },
  { img: "https://images.pexels.com/photos/7745980/pexels-photo-7745980.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 20 },
  { img: "https://images.pexels.com/photos/7746042/pexels-photo-7746042.jpeg?auto=compress&cs=tinysrgb&w=600", roomId: 20 },
];
const facilitiesRoomsData = [
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: true,
    isPrivateBathroom: false,
    isBalcony: false,
    isView: true,
    isTelevision: false,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: false,
    isBalcony: false,
    isView: true,
    isTelevision: true,
    isRefrigerator: false,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: true,
    isPrivateBathroom: false,
    isBalcony: false,
    isView: false,
    isTelevision: false,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: false,
    isRefrigerator: false,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: false,
    isPrivateBathroom: true,
    isBalcony: false,
    isView: false,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: false,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: false,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: false,
    isPrivateBathroom: true,
    isBalcony: false,
    isView: true,
    isTelevision: false,
    isRefrigerator: true,
    isWifi: false,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: false,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: false,
    isPrivateBathroom: false,
    isBalcony: false,
    isView: true,
    isTelevision: false,
    isRefrigerator: false,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: false,
    isBalcony: false,
    isView: false,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: false,
    isRefrigerator: false,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: false,
    isPrivateBathroom: true,
    isBalcony: false,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: false,
    isTelevision: false,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: true,
    isAirCondition: false,
    isPrivateBathroom: false,
    isBalcony: false,
    isView: false,
    isTelevision: false,
    isRefrigerator: true,
    isWifi: false,
    isShower: true,
    isBathtub: false,
  },
  {
    isSmoking: false,
    isAirCondition: true,
    isPrivateBathroom: true,
    isBalcony: true,
    isView: true,
    isTelevision: true,
    isRefrigerator: true,
    isWifi: true,
    isShower: true,
    isBathtub: false,
  }
];
const promotionData = [
  {
    name: "New Year Sale",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "NY2024",
    description: "Celebrate the New Year with a 20% discount on all bookings!",
    discountPercent: 20.0,
    discountValue: 0,
    minimumSpend: 5000.0,
    maxDiscount: 2000.0,
    usageLimit: 100,
    userLimit: 1,
    isActive: true,
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
  },
  {
    name: "Summer Splash",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "SUMMER23",
    description: "Enjoy your summer with a flat $500 discount on all hotels!",
    discountPercent: 0,
    discountValue: 500.0,
    minimumSpend: 3000.0,
    maxDiscount: 500.0,
    usageLimit: 50,
    userLimit: 1,
    isActive: true,
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-08-31"),
  },
  {
    name: "Weekend Getaway",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "WEEKEND",
    description: "10% discount for weekend bookings!",
    discountPercent: 10.0,
    discountValue: 0,
    minimumSpend: 2000.0,
    maxDiscount: 500.0,
    usageLimit: 200,
    userLimit: 2,
    isActive: true,
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-12-31"),
  },
  {
    name: "Flash Sale",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "FLASH50",
    description: "50% discount for a limited time!",
    discountPercent: 50.0,
    discountValue: 0,
    minimumSpend: 4000.0,
    maxDiscount: 1500.0,
    usageLimit: 30,
    userLimit: 1,
    isActive: false,
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-07"),
  },
  {
    name: "Christmas Special",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "XMAS2024",
    description: "Celebrate Christmas with a 25% discount on your next booking!",
    discountPercent: 25.0,
    discountValue: 0,
    minimumSpend: 6000.0,
    maxDiscount: 2500.0,
    usageLimit: 150,
    userLimit: 1,
    isActive: true,
    startDate: new Date("2024-12-20"),
    endDate: new Date("2024-12-26"),
  },
  {
    name: "Valentine's Day Special",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "LOVE2024",
    description: "Celebrate love with a 15% discount on all romantic getaways!",
    discountPercent: 15.0,
    discountValue: 0,
    minimumSpend: 4000.0,
    maxDiscount: 800.0,
    usageLimit: 75,
    userLimit: 2,
    isActive: true,
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-14"),
  },
  {
    name: "Spring Fling",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "SPRING23",
    description: "Enjoy a $200 discount on stays during spring!",
    discountPercent: 0,
    discountValue: 200.0,
    minimumSpend: 2500.0,
    maxDiscount: 200.0,
    usageLimit: 60,
    userLimit: 1,
    isActive: true,
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-05-31"),
  },
  {
    name: "Family Fun Discount",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "FAMILY20",
    description: "Get 20% off when booking family packages!",
    discountPercent: 20.0,
    discountValue: 0,
    minimumSpend: 6000.0,
    maxDiscount: 1200.0,
    usageLimit: 40,
    userLimit: 3,
    isActive: true,
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-09-30"),
  },
  {
    name: "Early Bird Special",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "EARLYBIRD",
    description: "Book at least 30 days in advance and get 10% off!",
    discountPercent: 10.0,
    discountValue: 0,
    minimumSpend: 3000.0,
    maxDiscount: 1000.0,
    usageLimit: 80,
    userLimit: 1,
    isActive: true,
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-11-30"),
  },
  {
    name: "Loyalty Reward",
    img: "https://e7.pngegg.com/pngimages/282/323/png-clipart-new-product-development-graphy-special-promo-text-rectangle-thumbnail.png",
    code: "LOYALTY20",
    description: "Get a special 20% discount for our loyal customers!",
    discountPercent: 20.0,
    discountValue: 0,
    minimumSpend: 5000.0,
    maxDiscount: 1500.0,
    usageLimit: 200,
    userLimit: 1,
    isActive: true,
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-12-31"),
  },
];
const userHavePromotionData = [
  { promotionId: 1, userId: 6, isUsed: true },
  { promotionId: 2, userId: 7, isUsed: true },
  { promotionId: 3, userId: 8, isUsed: true },
  { promotionId: 4, userId: 9, isUsed: false },
  { promotionId: 5, userId: 10, isUsed: false },
  { promotionId: 6, userId: 6, isUsed: true },
  { promotionId: 7, userId: 7, isUsed: false },
  { promotionId: 8, userId: 8, isUsed: true },
  { promotionId: 9, userId: 9, isUsed: false },
  { promotionId: 10, userId: 10, isUsed: true },
];
const bookingData = [
  {
    UUID: "uuid-12345",
    status: "CONFIRMED",
    totalPrice: 7500.0,
    checkinDate: new Date("2024-11-01"),
    checkoutDate: new Date("2024-11-05"),
    userId: 6, 
    hotelId: 1,
    userHavePromotionId: 1,
  },
  {
    UUID: "uuid-67890",
    status: "PENDING",
    totalPrice: 4500.0,
    checkinDate: new Date("2024-12-01"),
    checkoutDate: new Date("2024-12-03"),
    userId: 6,
    hotelId: 2,
    userHavePromotionId: 6, 
  },
  {
    UUID: "uuid-11121",
    status: "CANCELED",
    totalPrice: 5000.0,
    checkinDate: new Date("2024-12-10"),
    checkoutDate: new Date("2024-12-15"),
    userId: 7,
    hotelId: 3,
    userHavePromotionId: 2, 
  },
  {
    UUID: "uuid-22232",
    status: "CONFIRMED",
    totalPrice: 8800.0,
    checkinDate: new Date("2024-12-20"),
    checkoutDate: new Date("2024-12-25"),
    userId: 8,
    hotelId: 4,
    userHavePromotionId: 3,
  },
  {
    UUID: "uuid-33343",
    status: "REFUND",
    totalPrice: 9200.0,
    checkinDate: new Date("2025-01-10"),
    checkoutDate: new Date("2025-01-15"),
    userId: 9,
    hotelId: 5,
    userHavePromotionId: null,
  },
  {
    UUID: "uuid-44454",
    status: "CONFIRMED",
    totalPrice: 6700.0,
    checkinDate: new Date("2024-11-15"),
    checkoutDate: new Date("2024-11-20"),
    userId: 6,
    hotelId: 2,
    userHavePromotionId: 1,
  },
  {
    UUID: "uuid-55565",
    status: "PENDING",
    totalPrice: 4900.0,
    checkinDate: new Date("2024-11-25"),
    checkoutDate: new Date("2024-11-30"),
    userId: 7,
    hotelId: 3,
    userHavePromotionId: null, 
  },
  {
    UUID: "uuid-66676",
    status: "CANCELED",
    totalPrice: 5400.0,
    checkinDate: new Date("2025-01-05"),
    checkoutDate: new Date("2025-01-10"),
    userId: 8,
    hotelId: 4,
    userHavePromotionId: null, 
  },
  {
    UUID: "uuid-77787",
    status: "CONFIRMED",
    totalPrice: 8100.0,
    checkinDate: new Date("2024-12-05"),
    checkoutDate: new Date("2024-12-10"),
    userId: 10,
    hotelId: 5,
    userHavePromotionId: 5,
  },
  {
    UUID: "uuid-88898",
    status: "REFUND",
    totalPrice: 9200.0,
    checkinDate: new Date("2025-01-12"),
    checkoutDate: new Date("2025-01-18"),
    userId: 10,
    hotelId: 2,
    userHavePromotionId: null, 
  },
  {
    UUID: "uuid-99909",
    status: "CONFIRMED",
    totalPrice: 7200.0,
    checkinDate: new Date("2024-12-15"),
    checkoutDate: new Date("2024-12-20"),
    userId: 6,
    hotelId: 1,
    userHavePromotionId: 1,
  },
  {
    UUID: "uuid-10101",
    status: "PENDING",
    totalPrice: 6300.0,
    checkinDate: new Date("2024-12-21"),
    checkoutDate: new Date("2024-12-25"),
    userId: 7,
    hotelId: 5,
    userHavePromotionId: 2,
  },
  {
    UUID: "uuid-11112",
    status: "CONFIRMED",
    totalPrice: 8300.0,
    checkinDate: new Date("2025-01-01"),
    checkoutDate: new Date("2025-01-07"),
    userId: 10,
    hotelId: 3,
    userHavePromotionId: null,
  },
  {
    UUID: "uuid-12123",
    status: "CANCELED",
    totalPrice: 4600.0,
    checkinDate: new Date("2025-01-15"),
    checkoutDate: new Date("2025-01-20"),
    userId: 9,
    hotelId: 4,
    userHavePromotionId: 4,
  },
  {
    UUID: "uuid-13134",
    status: "REFUND",
    totalPrice: 9200.0,
    checkinDate: new Date("2025-01-20"),
    checkoutDate: new Date("2025-01-25"),
    userId: 8,
    hotelId: 3,
    userHavePromotionId: null, 
  },
];
const bookingRoomsData = [
  { bookingId: 1, roomId: 1, amountRoom: 1 }, 
  { bookingId: 2, roomId: 2, amountRoom: 1 },
  { bookingId: 3, roomId: 3, amountRoom: 1 }, 
  { bookingId: 4, roomId: 4, amountRoom: 2 },
  { bookingId: 5, roomId: 5, amountRoom: 1 },
  { bookingId: 6, roomId: 2, amountRoom: 1 },
  { bookingId: 7, roomId: 3, amountRoom: 1 }, 
  { bookingId: 8, roomId: 4, amountRoom: 1 }, 
  { bookingId: 9, roomId: 5, amountRoom: 2 }, 
  { bookingId: 10, roomId: 2, amountRoom: 1 },
  { bookingId: 11, roomId: 1, amountRoom: 1 },
  { bookingId: 12, roomId: 5, amountRoom: 1 },
  { bookingId: 13, roomId: 3, amountRoom: 1 },
  { bookingId: 14, roomId: 4, amountRoom: 1 },
  { bookingId: 15, roomId: 3, amountRoom: 1 },
];

const reviewData = [
  {
    content:
      "Amazing stay! The staff were so friendly and the room was perfect.",
    userId: 6,
    bookingId: 1, 
    hotelId: 1,
    rating: 5,
    img: "review1.jpg",
  },
  {
    content: "Had a great time! The pool area is fantastic.",
    userId: 10, 
    bookingId: 9, 
    hotelId: 5,
    rating: 4,
    img: null,
  },
  {
    content: "Exceptional experience! Will definitely come back again.",
    userId: 6, 
    bookingId: 11,
    hotelId: 1,
    rating: 5,
    img: "review3.jpg", 
  },
  {
    content: "Great service and clean rooms!",
    userId: 7, 
    bookingId: 6, 
    hotelId: 2,
    rating: 4,
    img: "review4.jpg",
  },
];
const paymentsData = [
  {
    paymentMethod: "CREDITCARD",
    bookingId: 1, 
  },
  {
    paymentMethod: "SCAN",
    bookingId: 2, 
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 3, 
  },
  {
    paymentMethod: "SCAN",
    bookingId: 4, 
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 5, 
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 6, 
  },
  {
    paymentMethod: "SCAN",
    bookingId: 7, 
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 8, 
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 9, 
  },
  {
    paymentMethod: "SCAN",
    bookingId: 10, 
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 11, 
  },
  {
    paymentMethod: "SCAN",
    bookingId: 12,
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 13, 
  },
  {
    paymentMethod: "SCAN",
    bookingId: 14,
  },
  {
    paymentMethod: "CREDITCARD",
    bookingId: 15, 
  },
];

async function run() {
  await prisma.user.createMany({ data: userData });
  await prisma.partner.createMany({ data: partnerData });
  await prisma.facilitiesHotel.createMany({ data: facilitiesHotelsData });
  await prisma.hotel.createMany({ data: hotelData });
  await prisma.facilitiesRoom.createMany({ data: facilitiesRoomsData });
  await prisma.room.createMany({ data: roomData });
  await prisma.roomImg.createMany({ data: roomImagesData });
  await prisma.promotion.createMany({ data: promotionData });
  await prisma.userHavePromotion.createMany({ data: userHavePromotionData });
  await prisma.booking.createMany({ data: bookingData });
  await prisma.bookingRoom.createMany({ data: bookingRoomsData });
  await prisma.review.createMany({ data: reviewData });
  await prisma.payment.createMany({ data: paymentsData });
}

run();
